name: Publish EpubManager NuGet Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      # Extract version from .csproj
      - name: Get version
        id: get-version
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils
          VERSION=$(xmllint --xpath "string(//Project/PropertyGroup/Version)" ./BookHeaven.EpubManager.csproj)
          echo "EpubManager version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Publish EpubManager package
      - name: Publish NuGet package
        run: |
          dotnet pack ./BookHeaven.EpubManager.csproj --configuration Release --output ./packages
          dotnet nuget add source \
            --username ${{ github.actor }} \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text \
            --name github "https://nuget.pkg.github.com/BookHeaven/index.json"
          dotnet nuget push ./packages/BookHeaven.EpubManager.$VERSION.nupkg \
            --source "github" \
            --api-key ${{ secrets.GITHUB_TOKEN }}
